export { default as Hero } from "./Hero"
export { default as Collection } from "./Collection"
export { default as BestFashion } from "./BestFashion"
export { default as BestSeller } from "./BestSeller"
export { default as Footer } from "./Footer"